version = 3.11.4
runner.dialect = Scala213
maxColumn = 80
docstrings.style = SpaceAsterisk
assumeStandardLibraryStripMargin = false

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = Sbt1
  }
}
